apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 3 # Number of replicas (instances) to run
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: mynode
          image: thenusan/cloudnative:7.2P
          ports:
            - containerPort: 3040 # Port your application listens on
